#pragma once

#include "descriptors.h"

struct HaEntityDescriptor
{
    const char *name;
    const char *icon;
    const char *unit;
    const char *deviceClass;
};

static constexpr const char *HA_UNIT_CELSIUS = "\xC2\xB0"
                                               "C";

static const HaEntityDescriptor HA_STATIC_DESCRIPTORS[] = {
    {DESCR_AC_In_Rating_Current, "current-ac", "A", "current"},
    {DESCR_AC_In_Rating_Voltage, "flash-triangle-outline", "V", "voltage"},
    {DESCR_AC_Out_Rating_Active_Power, "sine-wave", "W", "power"},
    {DESCR_AC_Out_Rating_Apparent_Power, "flash-outline", "VA", "apparent_power"},
    {DESCR_AC_Out_Rating_Current, "current-ac", "A", "current"},
    {DESCR_AC_Out_Rating_Frequency, "sine-wave", "Hz", "frequency"},
    {DESCR_AC_Out_Rating_Voltage, "flash-triangle-outline", "V", "voltage"},
    {DESCR_Battery_Bulk_Voltage, "car-battery", "V", "voltage"},
    {DESCR_Battery_Float_Voltage, "car-battery", "V", "voltage"},
    {DESCR_Battery_Rating_Voltage, "car-battery", "V", "voltage"},
    {DESCR_Battery_Recharge_Voltage, "battery-charging-high", "V", "voltage"},
    {DESCR_Battery_Redischarge_Voltage, "battery-charging-outline", "V", "voltage"},
    {DESCR_Battery_Type, "car-battery", "", ""},
    {DESCR_Battery_Under_Voltage, "battery-remove-outline", "V", "voltage"},
    {DESCR_Buzzer_Enabled, "tune-variant", "", ""},
    {DESCR_Charger_Source_Priority, "ev-station", "", ""},
    {DESCR_Current_Max_AC_Charging_Current, "current-ac", "A", "current"},
    {DESCR_Current_Max_Charging_Current, "battery-charging", "A", "current"},
    {DESCR_Data_Log_Pop_Up, "text-box-outline", "", ""},
    {DESCR_Device_Model, "chip", "", ""},
    {DESCR_Input_Voltage_Range, "flash-triangle-outline", "", ""},
    {DESCR_LCD_Backlight_Enabled, "lightbulb-on-outline", "", ""},
    {DESCR_LCD_Reset_To_Default_Enabled, "restore", "", ""},
    {DESCR_Machine_Type, "state-machine", "", ""},
    {DESCR_Max_Charging_Time_At_CV_Stage, "clock-time-eight-outline", "s", "duration"},
    {DESCR_Max_Discharging_Current, "battery-outline", "A", "current"},
    {DESCR_MPPT_String, "string-lights", "", ""},
    {DESCR_Operation_Logic, "cog-outline", "", ""},
    {DESCR_Output_Mode, "export", "", ""},
    {DESCR_Output_Source_Priority, "export", "", ""},
    {DESCR_Over_Temperature_Restart_Enabled, "restart", "", ""},
    {DESCR_Overload_Bypass_Enabled, "transit-connection-variant", "", ""},
    {DESCR_Overload_Restart_Enabled, "restart", "", ""},
    {DESCR_Parallel_Max_Num, "call-split", "", ""},
    {DESCR_Power_Saving_Enabled, "power-sleep", "", ""},
    {DESCR_Primary_Source_Interrupt_Alarm_Enabled, "alert-outline", "", ""},
    {DESCR_Protocol_ID, "protocol", "", ""},
    {DESCR_PV_OK_Condition_For_Parallel, "solar-panel", "", ""},
    {DESCR_PV_Power_Balance, "solar-panel", "", ""},
    {DESCR_Record_Fault_Code_Enabled, "playlist-check", "", ""},
    {DESCR_Solar_Power_Priority, "priority-high", "", ""},
    {DESCR_Topology, "transmission-tower", "", ""},
};

static const HaEntityDescriptor HA_LIVE_DESCRIPTORS[] = {
    {DESCR_AC_In_Frequency, "import", "Hz", "frequency"},
    {DESCR_AC_In_Frequency_L2, "import", "Hz", "frequency"},
    {DESCR_AC_In_Generation_Day, "import", "Wh", "energy"},
    {DESCR_AC_In_Generation_Month, "import", "Wh", "energy"},
    {DESCR_AC_In_Generation_Sum, "import", "Wh", "energy"},
    {DESCR_AC_In_Generation_Year, "import", "Wh", "energy"},
    {DESCR_AC_In_Voltage, "import", "V", "voltage"},
    {DESCR_AC_In_Voltage_L2, "import", "V", "voltage"},
    {DESCR_AC_Out_Frequency, "export", "Hz", "frequency"},
    {DESCR_AC_Out_Frequency_L2, "export", "Hz", "frequency"},
    {DESCR_AC_Out_Percent, "gauge", "%", ""},
    {DESCR_AC_Out_Percent_L2, "gauge", "%", ""},
    {DESCR_AC_Out_VA, "flash-outline", "VA", "apparent_power"},
    {DESCR_AC_Out_VA_L2, "flash-outline", "VA", "apparent_power"},
    {DESCR_AC_Out_Voltage, "export", "V", "voltage"},
    {DESCR_AC_Out_Voltage_L2, "export", "V", "voltage"},
    {DESCR_AC_Out_Watt, "flash", "W", "power"},
    {DESCR_AC_Out_Watt_L2, "flash", "W", "power"},
    {DESCR_AC_Output_Current, "current-ac", "A", "current"},
    {DESCR_AC_Output_Frequency, "export", "Hz", "frequency"},
    {DESCR_AC_Output_Power, "flash", "W", "power"},
    {DESCR_AC_Output_Voltage, "export", "V", "voltage"},
    {DESCR_ACDC_Power_Direction, "swap-horizontal", "", ""},
    {DESCR_Allow_SCC_On_Flag, "solar-power", "", ""},
    {DESCR_Battery_Charge_Current, "battery-charging-high", "A", "current"},
    {DESCR_Battery_Discharge_Current, "battery-minus-outline", "A", "current"},
    {DESCR_Battery_Load, "battery-outline", "A", "current"},
    {DESCR_Battery_Percent, "battery-high", "%", "battery"},
    {DESCR_Battery_Power_Direction, "battery-charging-high", "", ""},
    {DESCR_Battery_SCC_Volt, "battery-high", "V", "voltage"},
    {DESCR_Battery_SCC2_Volt, "battery-high", "V", "voltage"},
    {DESCR_Battery_Temperature, "thermometer-lines", HA_UNIT_CELSIUS, "temperature"},
    {DESCR_Battery_Voltage, "battery-high", "V", "voltage"},
    {DESCR_Battery_Voltage_L2, "battery-high", "V", "voltage"},
    {DESCR_Battery_Voltage_Offset_Fans_On, "fan", "", ""},
    {DESCR_Charge_Average_Current, "current-ac", "A", "current"},
    {DESCR_Configuration_State, "cog-outline", "", ""},
    {DESCR_Country, "earth", "", ""},
    {DESCR_Device_Status, "state-machine", "", ""},
    {DESCR_Device_Status_L2, "state-machine", "", ""},
    {DESCR_EEPROM_Version, "chip", "", ""},
    {DESCR_Fan_Lock_Status, "fan-alert", "", ""},
    {DESCR_Fan_Speed, "fan", "%", ""},
    {DESCR_Fault_Code, "alert-outline", "", ""},
    {DESCR_Inverter_Bus_Temperature, "thermometer-lines", HA_UNIT_CELSIUS, "temperature"},
    {DESCR_Inverter_Bus_Voltage, "flash-triangle-outline", "V", "voltage"},
    {DESCR_Inverter_Charge_State, "battery-heart-outline", "", ""},
    {DESCR_Inverter_Operation_Mode, "transmission-tower", "", ""},
    {DESCR_Inverter_Temperature, "thermometer-lines", HA_UNIT_CELSIUS, "temperature"},
    {DESCR_Line_Power_Direction, "export", "", ""},
    {DESCR_Load_Connection, "power-plug-outline", "", ""},
    {DESCR_Local_Parallel_ID, "call-split", "", ""},
    {DESCR_MPPT1_Charger_Status, "solar-power", "", ""},
    {DESCR_MPPT1_Charger_Temperature, "thermometer-lines", HA_UNIT_CELSIUS, "temperature"},
    {DESCR_MPPT2_Charger_Status, "solar-power", "", ""},
    {DESCR_MPPT2_Charger_Temperature, "thermometer-lines", HA_UNIT_CELSIUS, "temperature"},
    {DESCR_Negative_Battery_Voltage, "battery-minus-outline", "V", "voltage"},
    {DESCR_Output_Current, "current-ac", "A", "current"},
    {DESCR_Output_Load_Percent, "gauge", "%", ""},
    {DESCR_Output_Power, "flash", "W", "power"},
    {DESCR_Parallel_Warning, "alert-outline", "", ""},
    {DESCR_Positive_Battery_Voltage, "battery-plus-outline", "V", "voltage"},
    {DESCR_PV_Charging_Power, "solar-power-variant", "W", "power"},
    {DESCR_PV_Generation_Day, "solar-power-variant", "Wh", "energy"},
    {DESCR_PV_Generation_Month, "solar-power-variant", "Wh", "energy"},
    {DESCR_PV_Generation_Sum, "solar-power-variant", "Wh", "energy"},
    {DESCR_PV_Generation_Year, "solar-power-variant", "Wh", "energy"},
    {DESCR_PV_Input_Current, "solar-power-variant", "A", "current"},
    {DESCR_PV_Input_Power, "solar-power-variant", "W", "power"},
    {DESCR_PV_Input_Voltage, "solar-power-variant", "V", "voltage"},
    {DESCR_PV1_Input_Power, "solar-power-variant", "W", "power"},
    {DESCR_PV1_Input_Voltage, "solar-power-variant", "V", "voltage"},
    {DESCR_PV2_Charging_Power, "solar-power-variant", "W", "power"},
    {DESCR_PV2_Input_Current, "solar-power-variant", "A", "current"},
    {DESCR_PV2_Input_Power, "solar-power-variant", "W", "power"},
    {DESCR_PV2_Input_Voltage, "solar-power-variant", "V", "voltage"},
    {DESCR_SCC_Charge_Power, "solar-power", "W", "power"},
    {DESCR_SCC_Flag, "flag", "", ""},
    {DESCR_Solar_Feed_To_Grid_Power, "export", "W", "power"},
    {DESCR_Solar_Feed_To_Grid_Status, "export", "", ""},
    {DESCR_Status_Flag, "flag", "", ""},
    {DESCR_Sync_Frequency, "sine-wave", "Hz", "frequency"},
    {DESCR_Time_Until_Absorb_Charge, "clock-time-eight-outline", "s", "duration"},
    {DESCR_Time_Until_Float_Charge, "clock-time-eight-outline", "s", "duration"},
    {DESCR_Tracker_Temperature, "thermometer-lines", HA_UNIT_CELSIUS, "temperature"},
    {DESCR_Transformer_Temperature, "thermometer-lines", HA_UNIT_CELSIUS, "temperature"},
    {DESCR_Warning_Code, "alert-outline", "", ""},
};
