#pragma once

#include <cstring>

#include "descriptors.h"

struct HaEntityDescriptor
{
    const char *name;
    const char *icon;
    const char *unit;
    const char *deviceClass;
    const char *stateClass = nullptr;
    const char *displayName = nullptr;
    const char *defaultEntityId = nullptr;
};

static constexpr const char *HA_UNIT_CELSIUS = "\xC2\xB0"
                                               "C";

struct HaNameTranslation
{
    const char *key;
    const char *ru;
};

static const HaNameTranslation HA_RU_NAMES[] = {
    {DESCR_AC_In_Rating_Current, "Номинальный ток входа AC"},
    {DESCR_AC_In_Rating_Voltage, "Номинальное напряжение входа AC"},
    {DESCR_AC_Out_Rating_Active_Power, "Номинальная активная мощность выхода AC"},
    {DESCR_AC_Out_Rating_Apparent_Power, "Номинальная полная мощность выхода AC"},
    {DESCR_AC_Out_Rating_Current, "Номинальный ток выхода AC"},
    {DESCR_AC_Out_Rating_Frequency, "Номинальная частота выхода AC"},
    {DESCR_AC_Out_Rating_Voltage, "Номинальное напряжение выхода AC"},
    {DESCR_Battery_Bulk_Voltage, "Напряжение основного заряда АКБ"},
    {DESCR_Battery_Float_Voltage, "Напряжение поддерживающего заряда АКБ"},
    {DESCR_Battery_Rating_Voltage, "Номинальное напряжение АКБ"},
    {DESCR_Battery_Recharge_Voltage, "Напряжение перехода на заряд АКБ"},
    {DESCR_Battery_Redischarge_Voltage, "Напряжение возврата на АКБ"},
    {DESCR_Battery_Type, "Тип АКБ"},
    {DESCR_Battery_Equalization_Enabled, "Выравнивание АКБ"},
    {DESCR_Battery_Equalization_Active, "Выравнивание АКБ активно"},
    {DESCR_Battery_Under_Voltage, "Напряжение отключения АКБ"},
    {DESCR_Buzzer_Enabled, "Зуммер"},
    {DESCR_Charger_Source_Priority, "Приоритет источника зарядки"},
    {DESCR_Current_Max_AC_Charging_Current, "Максимальный ток зарядки от сети"},
    {DESCR_Current_Max_Charging_Current, "Максимальный ток зарядки АКБ"},
    {DESCR_Data_Log_Pop_Up, "Всплывающее окно журнала"},
    {DESCR_Device_Model, "Модель устройства"},
    {DESCR_Input_Voltage_Range, "Диапазон входного напряжения AC"},
    {DESCR_LCD_Backlight_Enabled, "Подсветка LCD"},
    {DESCR_LCD_Reset_To_Default_Enabled, "Сброс LCD к значениям по умолчанию"},
    {DESCR_Machine_Type, "Тип инвертора"},
    {DESCR_Max_Charging_Time_At_CV_Stage, "Максимальное время заряда CV"},
    {DESCR_Max_Discharging_Current, "Максимальный ток разряда АКБ"},
    {DESCR_MPPT_String, "Конфигурация MPPT"},
    {DESCR_Operation_Logic, "Логика работы"},
    {DESCR_Output_Mode, "Режим выхода"},
    {DESCR_Output_Source_Priority, "Приоритет источника нагрузки"},
    {DESCR_Over_Temperature_Restart_Enabled, "Перезапуск после перегрева"},
    {DESCR_Overload_Bypass_Enabled, "Байпас при перегрузке"},
    {DESCR_Overload_Restart_Enabled, "Перезапуск после перегрузки"},
    {DESCR_Parallel_Max_Num, "Максимальное число инверторов в параллели"},
    {DESCR_Power_Saving_Enabled, "Режим энергосбережения"},
    {DESCR_Primary_Source_Interrupt_Alarm_Enabled, "Сигнал потери основного источника"},
    {DESCR_Protocol_ID, "Протокол инвертора"},
    {DESCR_PV_OK_Condition_For_Parallel, "Условие PV для параллельной работы"},
    {DESCR_PV_Power_Balance, "Баланс мощности PV"},
    {DESCR_Record_Fault_Code_Enabled, "Запись кодов ошибок"},
    {DESCR_Solar_Power_Priority, "Приоритет солнечной энергии"},
    {DESCR_Solar_Feed_To_Grid_Enabled, "Разрешение отдачи в сеть"},
    {DESCR_Topology, "Топология инвертора"},

    {DESCR_AC_In_Frequency, "Частота входа AC"},
    {DESCR_AC_In_Frequency_L1, "Частота входа AC L1"},
    {DESCR_AC_In_Frequency_L2, "Частота входа AC L2"},
    {DESCR_AC_In_Watt, "Мощность входа AC"},
    {DESCR_AC_In_Generation_Day, "Энергия входа AC за день"},
    {DESCR_AC_In_Generation_Month, "Энергия входа AC за месяц"},
    {DESCR_AC_In_Generation_Sum, "Энергия входа AC всего"},
    {DESCR_AC_In_Generation_Year, "Энергия входа AC за год"},
    {DESCR_AC_In_Current_L1, "Ток входа AC L1"},
    {DESCR_AC_In_Current_L2, "Ток входа AC L2"},
    {DESCR_AC_In_Current_L3, "Ток входа AC L3"},
    {DESCR_AC_In_VA_L1, "Полная мощность входа AC L1"},
    {DESCR_AC_In_VA_L2, "Полная мощность входа AC L2"},
    {DESCR_AC_In_VA_L3, "Полная мощность входа AC L3"},
    {DESCR_AC_In_Voltage, "Напряжение входа AC"},
    {DESCR_AC_In_Voltage_L1, "Напряжение входа AC L1"},
    {DESCR_AC_In_Voltage_L2, "Напряжение входа AC L2"},
    {DESCR_AC_In_Voltage_L3, "Напряжение входа AC L3"},
    {DESCR_AC_In_Watt_L1, "Мощность входа AC L1"},
    {DESCR_AC_In_Watt_L2, "Мощность входа AC L2"},
    {DESCR_AC_In_Watt_L3, "Мощность входа AC L3"},
    {DESCR_AC_Out_Current_L1, "Ток выхода AC L1"},
    {DESCR_AC_Out_Current_L2, "Ток выхода AC L2"},
    {DESCR_AC_Out_Current_L3, "Ток выхода AC L3"},
    {DESCR_AC_Out_Frequency, "Частота выхода AC"},
    {DESCR_AC_Out_Frequency_L1, "Частота выхода AC L1"},
    {DESCR_AC_Out_Frequency_L2, "Частота выхода AC L2"},
    {DESCR_AC_Out_Percent, "Загрузка выхода AC"},
    {DESCR_AC_Out_Percent_L1, "Загрузка выхода AC L1"},
    {DESCR_AC_Out_Percent_L2, "Загрузка выхода AC L2"},
    {DESCR_AC_Out_Percent_L3, "Загрузка выхода AC L3"},
    {DESCR_AC_Out_VA, "Полная мощность выхода AC"},
    {DESCR_AC_Out_VA_L1, "Полная мощность выхода AC L1"},
    {DESCR_AC_Out_VA_L2, "Полная мощность выхода AC L2"},
    {DESCR_AC_Out_VA_L3, "Полная мощность выхода AC L3"},
    {DESCR_AC_Out_Voltage, "Напряжение выхода AC"},
    {DESCR_AC_Out_Voltage_L1, "Напряжение выхода AC L1"},
    {DESCR_AC_Out_Voltage_L2, "Напряжение выхода AC L2"},
    {DESCR_AC_Out_Voltage_L3, "Напряжение выхода AC L3"},
    {DESCR_AC_Out_Watt, "Мощность выхода AC"},
    {DESCR_AC_Out_Watt_L1, "Мощность выхода AC L1"},
    {DESCR_AC_Out_Watt_L2, "Мощность выхода AC L2"},
    {DESCR_AC_Out_Watt_L3, "Мощность выхода AC L3"},
    {DESCR_AC_Output_Current, "Ток выхода AC"},
    {DESCR_AC_Output_Frequency, "Частота выхода AC"},
    {DESCR_AC_Output_Power, "Мощность выхода AC"},
    {DESCR_AC_Output_Voltage, "Напряжение выхода AC"},
    {DESCR_ACDC_Power_Direction, "Направление мощности AC/DC"},
    {DESCR_Allow_SCC_On_Flag, "Разрешение солнечного контроллера"},
    {DESCR_Battery_Charge_Current, "Ток заряда АКБ"},
    {DESCR_Battery_Average_Current, "Средний ток АКБ"},
    {DESCR_Battery_Average_Power, "Средняя мощность АКБ"},
    {DESCR_Battery_Charging_Power, "Мощность зарядки АКБ (инвертор)"},
    {DESCR_Battery_Charging_Power_Calculated, "Мощность зарядки АКБ"},
    {DESCR_Battery_Discharging_Power_Calculated, "Мощность разряда АКБ"},
    {DESCR_Battery_Charge_Energy, "Зарядка батареи"},
    {DESCR_Battery_Discharge_Energy, "Разрядка батареи"},
    {DESCR_Battery_Discharge_Current, "Ток разряда АКБ"},
    {DESCR_Battery_Load, "Ток АКБ с направлением"},
    {DESCR_Battery_Percent, "Заряд АКБ"},
    {DESCR_Battery_Power_Direction, "Направление мощности АКБ"},
    {DESCR_Battery_SCC_Volt, "Напряжение АКБ от SCC"},
    {DESCR_Battery_SCC2_Volt, "Напряжение АКБ от SCC2"},
    {DESCR_Battery_Temperature, "Температура АКБ"},
    {DESCR_Battery_Voltage, "Напряжение АКБ"},
    {DESCR_Battery_Voltage_L2, "Напряжение АКБ L2"},
    {DESCR_Battery_Voltage_Offset_Fans_On, "Смещение напряжения АКБ при включённых вентиляторах"},
    {DESCR_Charge_Average_Current, "Средний ток зарядки"},
    {DESCR_Configuration_State, "Состояние конфигурации"},
    {DESCR_Country, "Регион устройства"},
    {DESCR_Device_Status, "Состояние устройства"},
    {DESCR_Device_Status_L2, "Состояние устройства L2"},
    {DESCR_EEPROM_Version, "Версия EEPROM"},
    {DESCR_Fan_Lock_Status, "Блокировка вентилятора"},
    {DESCR_Fan_Speed, "Скорость вентилятора"},
    {DESCR_Fault_Code, "Код ошибки"},
    {DESCR_Inverter_Bus_Temperature, "Температура шины инвертора"},
    {DESCR_Inverter_Bus_Voltage, "Напряжение шины инвертора"},
    {DESCR_Inverter_Charge_State, "Стадия зарядки"},
    {DESCR_Inverter_Operation_Mode, "Режим работы инвертора"},
    {DESCR_Inverter_Temperature, "Температура инвертора"},
    {DESCR_Home_Load_Active_Power_L1, "Мощность нагрузки дома L1"},
    {DESCR_Home_Load_Active_Power_L2, "Мощность нагрузки дома L2"},
    {DESCR_Home_Load_Active_Power_L3, "Мощность нагрузки дома L3"},
    {DESCR_Line_Power_Direction, "Направление мощности линии"},
    {DESCR_Load_Connection, "Подключение нагрузки"},
    {DESCR_Local_Parallel_ID, "ID инвертора в параллели"},
    {DESCR_MPPT1_Charger_Status, "Состояние зарядного MPPT1"},
    {DESCR_MPPT1_Charger_Temperature, "Температура зарядного MPPT1"},
    {DESCR_MPPT2_Charger_Status, "Состояние зарядного MPPT2"},
    {DESCR_MPPT2_Charger_Temperature, "Температура зарядного MPPT2"},
    {DESCR_Negative_Battery_Voltage, "Отрицательное напряжение АКБ"},
    {DESCR_Output_Current, "Выходной ток"},
    {DESCR_Output_Load_Percent, "Загрузка выхода"},
    {DESCR_Output_Power, "Выходная мощность"},
    {DESCR_Parallel_Warning, "Предупреждение параллельной работы"},
    {DESCR_Positive_Battery_Voltage, "Положительное напряжение АКБ"},
    {DESCR_PV_Charging_Power, "Мощность зарядки от PV"},
    {DESCR_PV_Charge_Current, "Ток зарядки от PV"},
    {DESCR_PV_Generation_Day, "Энергия PV за день"},
    {DESCR_PV_Generation_Month, "Энергия PV за месяц"},
    {DESCR_PV_Generation_Sum, "Энергия PV всего"},
    {DESCR_PV_Generation_Year, "Энергия PV за год"},
    {DESCR_PV_Input_Power, "Входная мощность PV"},
    {DESCR_PV_Input_Voltage, "Входное напряжение PV"},
    {DESCR_PV1_Input_Current, "Входной ток PV1"},
    {DESCR_PV1_Input_Power, "Входная мощность PV1"},
    {DESCR_PV1_Input_Voltage, "Входное напряжение PV1"},
    {DESCR_PV2_Charging_Power, "Мощность зарядки от PV2"},
    {DESCR_PV2_Input_Current, "Входной ток PV2"},
    {DESCR_PV2_Input_Power, "Входная мощность PV2"},
    {DESCR_PV2_Input_Voltage, "Входное напряжение PV2"},
    {DESCR_SCC_Charge_Power, "Мощность зарядки SCC"},
    {DESCR_SCC_Flag, "Состояние SCC"},
    {DESCR_Solar_Feed_To_Grid_Power, "Мощность отдачи в сеть"},
    {DESCR_Solar_Feed_To_Grid_Status, "Состояние отдачи в сеть"},
    {DESCR_Status_Flag, "Флаги состояния"},
    {DESCR_Sync_Frequency, "Частота синхронизации"},
    {DESCR_Time_Until_Absorb_Charge, "Время до стадии Absorb"},
    {DESCR_Time_Until_Float_Charge, "Время до стадии Float"},
    {DESCR_Tracker_Temperature, "Температура MPPT-трекера"},
    {DESCR_Transformer_Temperature, "Температура трансформатора"},
    {DESCR_Warning_Code, "Код предупреждения"},
};

inline const char *haRussianName(const char *key)
{
    if (key == nullptr)
    {
        return nullptr;
    }

    for (const HaNameTranslation &entry : HA_RU_NAMES)
    {
        if (strcmp(entry.key, key) == 0)
        {
            return entry.ru;
        }
    }
    return nullptr;
}

static const HaEntityDescriptor HA_STATIC_DESCRIPTORS[] = {
    {DESCR_AC_In_Rating_Current, "current-ac", "A", "current"},
    {DESCR_AC_In_Rating_Voltage, "flash-triangle-outline", "V", "voltage"},
    {DESCR_AC_Out_Rating_Active_Power, "sine-wave", "W", "power"},
    {DESCR_AC_Out_Rating_Apparent_Power, "flash-outline", "VA", "apparent_power"},
    {DESCR_AC_Out_Rating_Current, "current-ac", "A", "current"},
    {DESCR_AC_Out_Rating_Frequency, "sine-wave", "Hz", "frequency"},
    {DESCR_AC_Out_Rating_Voltage, "flash-triangle-outline", "V", "voltage"},
    {DESCR_Battery_Bulk_Voltage, "car-battery", "V", "voltage"},
    {DESCR_Battery_Float_Voltage, "car-battery", "V", "voltage"},
    {DESCR_Battery_Rating_Voltage, "car-battery", "V", "voltage"},
    {DESCR_Battery_Recharge_Voltage, "battery-charging-high", "V", "voltage"},
    {DESCR_Battery_Redischarge_Voltage, "battery-charging-outline", "V", "voltage"},
    {DESCR_Battery_Type, "car-battery", "", ""},
    {DESCR_Battery_Equalization_Enabled, "battery-sync-outline", "", ""},
    {DESCR_Battery_Under_Voltage, "battery-remove-outline", "V", "voltage"},
    {DESCR_Buzzer_Enabled, "tune-variant", "", ""},
    {DESCR_Charger_Source_Priority, "ev-station", "", ""},
    {DESCR_Current_Max_AC_Charging_Current, "current-ac", "A", "current"},
    {DESCR_Current_Max_Charging_Current, "battery-charging", "A", "current"},
    {DESCR_Data_Log_Pop_Up, "text-box-outline", "", ""},
    {DESCR_Device_Model, "chip", "", ""},
    {DESCR_Input_Voltage_Range, "flash-triangle-outline", "", ""},
    {DESCR_LCD_Backlight_Enabled, "lightbulb-on-outline", "", ""},
    {DESCR_LCD_Reset_To_Default_Enabled, "restore", "", ""},
    {DESCR_Machine_Type, "state-machine", "", ""},
    {DESCR_Max_Charging_Time_At_CV_Stage, "clock-time-eight-outline", "min", "duration"},
    {DESCR_Max_Discharging_Current, "battery-outline", "A", "current"},
    {DESCR_MPPT_String, "string-lights", "", ""},
    {DESCR_Operation_Logic, "cog-outline", "", ""},
    {DESCR_Output_Mode, "export", "", ""},
    {DESCR_Output_Source_Priority, "export", "", ""},
    {DESCR_Over_Temperature_Restart_Enabled, "restart", "", ""},
    {DESCR_Overload_Bypass_Enabled, "transit-connection-variant", "", ""},
    {DESCR_Overload_Restart_Enabled, "restart", "", ""},
    {DESCR_Parallel_Max_Num, "call-split", "", ""},
    {DESCR_Power_Saving_Enabled, "power-sleep", "", ""},
    {DESCR_Primary_Source_Interrupt_Alarm_Enabled, "alert-outline", "", ""},
    {DESCR_Protocol_ID, "protocol", "", ""},
    {DESCR_PV_OK_Condition_For_Parallel, "solar-panel", "", ""},
    {DESCR_PV_Power_Balance, "solar-panel", "", ""},
    {DESCR_Record_Fault_Code_Enabled, "playlist-check", "", ""},
    {DESCR_Solar_Power_Priority, "priority-high", "", ""},
    {DESCR_Solar_Feed_To_Grid_Enabled, "transmission-tower-export", "", ""},
    {DESCR_Topology, "transmission-tower", "", ""},
};

static const HaEntityDescriptor HA_LIVE_DESCRIPTORS[] = {
    {DESCR_AC_In_Frequency, "import", "Hz", "frequency", "measurement"},
    {DESCR_AC_In_Frequency_L1, "import", "Hz", "frequency", "measurement"},
    {DESCR_AC_In_Frequency_L2, "import", "Hz", "frequency", "measurement"},
    {DESCR_AC_In_Watt, "transmission-tower-import", "W", "power", "measurement"},
    {DESCR_AC_In_Generation_Day, "import", "Wh", "energy"},
    {DESCR_AC_In_Generation_Month, "import", "Wh", "energy"},
    {DESCR_AC_In_Generation_Sum, "import", "Wh", "energy", "total_increasing"},
    {DESCR_AC_In_Generation_Year, "import", "Wh", "energy"},
    {DESCR_AC_In_Current_L1, "current-ac", "A", "current", "measurement"},
    {DESCR_AC_In_Current_L2, "current-ac", "A", "current", "measurement"},
    {DESCR_AC_In_Current_L3, "current-ac", "A", "current", "measurement"},
    {DESCR_AC_In_VA_L1, "flash-outline", "VA", "apparent_power", "measurement"},
    {DESCR_AC_In_VA_L2, "flash-outline", "VA", "apparent_power", "measurement"},
    {DESCR_AC_In_VA_L3, "flash-outline", "VA", "apparent_power", "measurement"},
    {DESCR_AC_In_Voltage, "import", "V", "voltage", "measurement"},
    {DESCR_AC_In_Voltage_L1, "import", "V", "voltage", "measurement"},
    {DESCR_AC_In_Voltage_L2, "import", "V", "voltage", "measurement"},
    {DESCR_AC_In_Voltage_L3, "import", "V", "voltage", "measurement"},
    {DESCR_AC_In_Watt_L1, "transmission-tower-import", "W", "power", "measurement"},
    {DESCR_AC_In_Watt_L2, "transmission-tower-import", "W", "power", "measurement"},
    {DESCR_AC_In_Watt_L3, "transmission-tower-import", "W", "power", "measurement"},
    {DESCR_AC_Out_Current_L1, "current-ac", "A", "current", "measurement"},
    {DESCR_AC_Out_Current_L2, "current-ac", "A", "current", "measurement"},
    {DESCR_AC_Out_Current_L3, "current-ac", "A", "current", "measurement"},
    {DESCR_AC_Out_Frequency, "export", "Hz", "frequency", "measurement"},
    {DESCR_AC_Out_Frequency_L1, "export", "Hz", "frequency", "measurement"},
    {DESCR_AC_Out_Frequency_L2, "export", "Hz", "frequency", "measurement"},
    {DESCR_AC_Out_Percent, "gauge", "%", ""},
    {DESCR_AC_Out_Percent_L1, "gauge", "%", ""},
    {DESCR_AC_Out_Percent_L2, "gauge", "%", ""},
    {DESCR_AC_Out_Percent_L3, "gauge", "%", ""},
    {DESCR_AC_Out_VA, "flash-outline", "VA", "apparent_power", "measurement"},
    {DESCR_AC_Out_VA_L1, "flash-outline", "VA", "apparent_power", "measurement"},
    {DESCR_AC_Out_VA_L2, "flash-outline", "VA", "apparent_power", "measurement"},
    {DESCR_AC_Out_VA_L3, "flash-outline", "VA", "apparent_power", "measurement"},
    {DESCR_AC_Out_Voltage, "export", "V", "voltage", "measurement"},
    {DESCR_AC_Out_Voltage_L1, "export", "V", "voltage", "measurement"},
    {DESCR_AC_Out_Voltage_L2, "export", "V", "voltage", "measurement"},
    {DESCR_AC_Out_Voltage_L3, "export", "V", "voltage", "measurement"},
    {DESCR_AC_Out_Watt, "flash", "W", "power", "measurement"},
    {DESCR_AC_Out_Watt_L1, "flash", "W", "power", "measurement"},
    {DESCR_AC_Out_Watt_L2, "flash", "W", "power", "measurement"},
    {DESCR_AC_Out_Watt_L3, "flash", "W", "power", "measurement"},
    {DESCR_AC_Output_Current, "current-ac", "A", "current", "measurement"},
    {DESCR_AC_Output_Frequency, "export", "Hz", "frequency", "measurement"},
    {DESCR_AC_Output_Power, "flash", "W", "power", "measurement"},
    {DESCR_AC_Output_Voltage, "export", "V", "voltage", "measurement"},
    {DESCR_ACDC_Power_Direction, "swap-horizontal", "", ""},
    {DESCR_Allow_SCC_On_Flag, "solar-power", "", ""},
    {DESCR_Battery_Charge_Current, "battery-charging-high", "A", "current", "measurement"},
    {DESCR_Battery_Average_Current, "battery-outline", "A", "current", "measurement"},
    {DESCR_Battery_Average_Power, "battery-outline", "W", "power", "measurement"},
    {DESCR_Battery_Charging_Power, "battery-charging-high", "W", "power", "measurement"},
    {DESCR_Battery_Charging_Power_Calculated, "battery-charging-high", "W", "power", "measurement", "Battery Charging Power", "sensor.battery_charging_power"},
    {DESCR_Battery_Discharging_Power_Calculated, "battery-minus-outline", "W", "power", "measurement", "Battery Discharging Power", "sensor.battery_discharging_power"},
    {DESCR_Battery_Equalization_Active, "battery-sync", "", ""},
    {DESCR_Battery_Charge_Energy, "battery-plus", "kWh", "energy", "total_increasing", "Зарядка батареи", "sensor.battery_total_charge_energy"},
    {DESCR_Battery_Discharge_Energy, "battery-minus", "kWh", "energy", "total_increasing", "Разрядка батареи", "sensor.battery_total_discharge_energy"},
    {DESCR_Battery_Discharge_Current, "battery-minus-outline", "A", "current", "measurement"},
    {DESCR_Battery_Load, "battery-outline", "A", "current", "measurement"},
    {DESCR_Battery_Percent, "battery-high", "%", "battery", "measurement"},
    {DESCR_Battery_Power_Direction, "battery-charging-high", "", ""},
    {DESCR_Battery_SCC_Volt, "battery-high", "V", "voltage", "measurement"},
    {DESCR_Battery_SCC2_Volt, "battery-high", "V", "voltage", "measurement"},
    {DESCR_Battery_Temperature, "thermometer-lines", HA_UNIT_CELSIUS, "temperature", "measurement"},
    {DESCR_Battery_Voltage, "battery-high", "V", "voltage", "measurement"},
    {DESCR_Battery_Voltage_L2, "battery-high", "V", "voltage", "measurement"},
    {DESCR_Battery_Voltage_Offset_Fans_On, "fan", "", ""},
    {DESCR_Charge_Average_Current, "current-ac", "A", "current", "measurement"},
    {DESCR_Configuration_State, "cog-outline", "", ""},
    {DESCR_Country, "earth", "", ""},
    {DESCR_Device_Status, "state-machine", "", ""},
    {DESCR_Device_Status_L2, "state-machine", "", ""},
    {DESCR_EEPROM_Version, "chip", "", ""},
    {DESCR_Fan_Lock_Status, "fan-alert", "", ""},
    {DESCR_Fan_Speed, "fan", "%", ""},
    {DESCR_Fault_Code, "alert-outline", "", ""},
    {DESCR_Inverter_Bus_Temperature, "thermometer-lines", HA_UNIT_CELSIUS, "temperature", "measurement"},
    {DESCR_Inverter_Bus_Voltage, "flash-triangle-outline", "V", "voltage", "measurement"},
    {DESCR_Inverter_Charge_State, "battery-heart-outline", "", ""},
    {DESCR_Inverter_Operation_Mode, "transmission-tower", "", ""},
    {DESCR_Inverter_Temperature, "thermometer-lines", HA_UNIT_CELSIUS, "temperature", "measurement"},
    {DESCR_Home_Load_Active_Power_L1, "home-lightning-bolt-outline", "W", "power", "measurement"},
    {DESCR_Home_Load_Active_Power_L2, "home-lightning-bolt-outline", "W", "power", "measurement"},
    {DESCR_Home_Load_Active_Power_L3, "home-lightning-bolt-outline", "W", "power", "measurement"},
    {DESCR_Line_Power_Direction, "export", "", ""},
    {DESCR_Load_Connection, "power-plug-outline", "", ""},
    {DESCR_Local_Parallel_ID, "call-split", "", ""},
    {DESCR_MPPT1_Charger_Status, "solar-power", "", ""},
    {DESCR_MPPT1_Charger_Temperature, "thermometer-lines", HA_UNIT_CELSIUS, "temperature", "measurement"},
    {DESCR_MPPT2_Charger_Status, "solar-power", "", ""},
    {DESCR_MPPT2_Charger_Temperature, "thermometer-lines", HA_UNIT_CELSIUS, "temperature", "measurement"},
    {DESCR_Negative_Battery_Voltage, "battery-minus-outline", "V", "voltage", "measurement"},
    {DESCR_Output_Current, "current-ac", "A", "current", "measurement"},
    {DESCR_Output_Load_Percent, "gauge", "%", ""},
    {DESCR_Output_Power, "flash", "W", "power", "measurement"},
    {DESCR_Parallel_Warning, "alert-outline", "", ""},
    {DESCR_Positive_Battery_Voltage, "battery-plus-outline", "V", "voltage", "measurement"},
    {DESCR_PV_Charging_Power, "solar-power-variant", "W", "power", "measurement"},
    {DESCR_PV_Charge_Current, "solar-power-variant", "A", "current", "measurement"},
    {DESCR_PV_Generation_Day, "solar-power-variant", "Wh", "energy"},
    {DESCR_PV_Generation_Month, "solar-power-variant", "Wh", "energy"},
    {DESCR_PV_Generation_Sum, "solar-power-variant", "Wh", "energy", "total_increasing"},
    {DESCR_PV_Generation_Year, "solar-power-variant", "Wh", "energy"},
    {DESCR_PV_Input_Power, "solar-power-variant", "W", "power", "measurement"},
    {DESCR_PV_Total_Input_Power, "solar-power-variant", "W", "power", "measurement"},
    {DESCR_PV_Input_Voltage, "solar-power-variant", "V", "voltage", "measurement"},
    {DESCR_PV1_Input_Current, "solar-power-variant", "A", "current", "measurement"},
    {DESCR_PV1_Input_Power, "solar-power-variant", "W", "power", "measurement"},
    {DESCR_PV1_Input_Voltage, "solar-power-variant", "V", "voltage", "measurement"},
    {DESCR_PV2_Charging_Power, "solar-power-variant", "W", "power", "measurement"},
    {DESCR_PV2_Input_Current, "solar-power-variant", "A", "current", "measurement"},
    {DESCR_PV2_Input_Power, "solar-power-variant", "W", "power", "measurement"},
    {DESCR_PV2_Input_Voltage, "solar-power-variant", "V", "voltage", "measurement"},
    {DESCR_SCC_Charge_Power, "solar-power", "W", "power", "measurement"},
    {DESCR_SCC_Flag, "flag", "", ""},
    {DESCR_Solar_Feed_To_Grid_Power, "export", "W", "power", "measurement"},
    {DESCR_Solar_Feed_To_Grid_Status, "export", "", ""},
    {DESCR_Status_Flag, "flag", "", ""},
    {DESCR_Sync_Frequency, "sine-wave", "Hz", "frequency", "measurement"},
    {DESCR_Time_Until_Absorb_Charge, "clock-time-eight-outline", "s", "duration"},
    {DESCR_Time_Until_Float_Charge, "clock-time-eight-outline", "s", "duration"},
    {DESCR_Tracker_Temperature, "thermometer-lines", HA_UNIT_CELSIUS, "temperature", "measurement"},
    {DESCR_Transformer_Temperature, "thermometer-lines", HA_UNIT_CELSIUS, "temperature", "measurement"},
    {DESCR_Warning_Code, "alert-outline", "", ""},
};

