
#define DEFAULT_KEY_BATTERY_API "ZQZVTOCAQTYW2EB9"
#define DEFAULT_KEY_CHARGER_API "LI18WECZ0GDYCC9R"
#define DEFAULT_KEY_LOAD_API "GAHO2S5KRMZOZUXK"
#define DEFAULT_KEY_READCONFIG_API ""
#define DEFAULT_KEY_WRITECONFIG_API ""
