const char HTML_SETTINGSEDIT[] PROGMEM ="<figure class=\"text-center\"><h1>Edit Configuration</h1></figure>\n"
                                        "<form method=\"POST\" action=\"/settingssave\" enctype=\"multipart/form-data\">\n"
                                        "<div class=\"input-group mb-3\">\n"
                                        "<span class=\"input-group-text w-50\" id=\"devicenamedesc\">Device Name</span>"
                                        "<input type=\"text\" class=\"form-control\" aria-describedby=\"devicenamedesc\" id=\"devicename\" name=\"post_deviceName\" value=\"\">\n"
                                        "</div>\n"
                                        "<div class=\"input-group mb-2\">\n"
                                        "<span class=\"input-group-text w-50\" id=\"mqttserverdesc\">MQTT Server</span>"
                                        "<input type=\"text\" class=\"form-control\" aria-describedby=\"mqttserverdesc\" id=\"mqttserver\" name=\"post_mqttServer\" value=\"\">\n"
                                        "</div>\n"
                                        "<div class=\"input-group mb-2\">\n"
                                        "<span class=\"input-group-text w-50\" id=\"mqttportdesc\">MQTT Port</span>"
                                        "<input type=\"text\" class=\"form-control\" aria-describedby=\"mqttportdesc\" id=\"mqttport\" name=\"post_mqttPort\" value=\"\">\n"
                                        "</div>\n"
                                        "<div class=\"input-group mb-2\">\n"
                                        "<span class=\"input-group-text w-50\" id=\"mqttuserdesc\">MQTT Port</span>"
                                        "<input type=\"text\" class=\"form-control\" aria-describedby=\"mqttuserdesc\" id=\"mqttuser\" name=\"post_mqttUser\" value=\"\">\n"
                                        "</div>\n"
                                        "<div class=\"input-group mb-2\">\n"
                                        "<span class=\"input-group-text w-50\" id=\"mqttpassworddesc\">MQTT Password</span>"
                                        "<input type=\"text\" class=\"form-control\" aria-describedby=\"mqttpassworddesc\" id=\"mqttpassword\" name=\"post_mqttPassword\" value=\"\">\n"
                                        "</div>\n"
                                        "<div class=\"input-group mb-2\">\n"
                                        "<span class=\"input-group-text w-50\" id=\"mqtttopicdesc\">MQTT Topic</span>"
                                        "<input type=\"text\" class=\"form-control\" aria-describedby=\"mqtttopicdesc\" id=\"mqtttopic\" name=\"post_mqttTopic\" value=\"\">\n"
                                        "</div>\n"
                                        "<div class=\"input-group mb-2\">\n"
                                        "<span class=\"input-group-text w-50\" id=\"mqttrefreshdesc\">MQTT Refresh</span>"
                                        "<input type=\"text\" class=\"form-control\" aria-describedby=\"mqttrefreshdesc\" id=\"mqttrefresh\" id=\"mqttrefresh\" name=\"post_mqttRefresh\" value=\"\">\n"
                                        "</div>\n"
                                        "<div class=\"input-group mb-2\">\n"
                                        "<label class=\"input-group-text w-50\" for=\"devicetype\">Inverter Type</label>\n"
                                        "<select class=\"form-select\" id=\"devicetype\" name=\"post_deviceType\">\n"
                                        "<option value=\"PCM\">PCM</option>\n"
                                        "<option value=\"MPI\">MPI</option>\n"
                                        "<option value=\"PIP\">PIP</option>\n"
                                        "</select>\n"
                                        "</div>"
                                        
                                        "<div class=\"d-grid gap-2\">\n"
                                        "<input class=\"btn btn-primary\" type=\"submit\" value=\"Save settings\">\n"
                                        "</form>\n"
                                        "<a class=\"btn btn-primary\" href=\"/settings\" role=\"button\">Back</a>\n"
                                        "</div>"

                                    "<script>\n"
                                     "        $(document).ready(function(load) {\n"
                                     "        $.ajax({\n"
                                     "            url: \"livedataAjax\",\n"
                                     "            data: {},\n"
                                     "            type: \"get\",\n"
                                     "            dataType: \"json\",\n"
                                     "               cache: false,\n"
                                     "                success: function (data) {\n"
                                     "               document.getElementById(\"devicename\").value = data.device_name;\n"
                                     "               document.getElementById(\"mqttserver\").value = data.mqtt_server;\n"
                                     "               document.getElementById(\"mqttport\").value = data.mqtt_port;\n"
                                     "               document.getElementById(\"mqtttopic\").value = data.mqtt_topic;\n"
                                     "               document.getElementById(\"mqttuser\").value = data.mqtt_user;\n"
                                     "               document.getElementById(\"mqttpassword\").value = data.mqtt_password;\n"
                                     "               document.getElementById(\"mqttrefresh\").value = data.mqtt_refresh;\n"
                                     "               document.getElementById(\"devicetype\").value = data.device_type;\n"
                                     "            }\n"
                                     "        });\n"
                                     "        });\n"
                                     "</script>\n";

String sendHTMLsettingsEdit()
{
    String ptr = HTMLhead();
    ptr += FPSTR(HTML_SETTINGSEDIT);
    ptr += HTMLfoot();
    return ptr;
}